[__config__]
oldver = "container.json"
newver = "container.new.json"

[python-latest]
source = "container"
container = "library/python"
registry = "docker.io"

[python-stable]
source = "container"
container = "library/python"
registry = "docker.io"
include_regex = '3.12.\d+'

[debian-latest]
source = "container"
container = "library/debian"
registry = "docker.io"

[debian-bookworm]
source = "container"
container = "library/debian"
registry = "docker.io"
include_regex = 'bookworm-\d{8}'

[ubuntu-latest]
source = "container"
container = "library/ubuntu"
registry = "docker.io"

[alpine]
source = "container"
container = "library/alpine"
registry = "docker.io"

[nginx]
source = "container"
container = "library/nginx"
registry = "docker.io"

[postgres]
source = "container"
container = "library/postgres"
registry = "docker.io"

