[__config__]
oldver = "debianpkg.json"
newver = "debianpkg.new.json"

[nginx-buster]
source = "debianpkg"
debianpkg = "nginx"
suite = "buster"

[nginx-extras-buster]
source = "debianpkg"
debianpkg = "nginx-extras"
suite = "buster"

[nginx-bullseye]
source = "debianpkg"
debianpkg = "nginx"
suite = "bullseye"

[nginx-extras-bullseye]
source = "debianpkg"
debianpkg = "nginx-extras"
suite = "bullseye"


