name: 'New Version Checker'

# **What it does**: Checks software new releases, then notify me.

on:
  push:
    branches:
      - main
  schedule:
    - cron: '20 16 * * *' # Run everyday at 16:20 UTC

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install nvchecker
        run: sudo apt-get update && sudo apt-get install -y nvchecker

      - name: Check versions
        run: nvchecker -t 3 -c ./config.toml

      - name: Compare versions
        run: |
          nvcmp -c ./config.toml | tee /tmp/nvcmp_out.txt
          echo 'NV<<EOF' >> $GITHUB_ENV
          cat /tmp/nvcmp_out.txt | sed 's/^/- /' >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: Create pull request
        if: ${{ env.NV }} && github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Bump report
          branch: actions_new_version
          delete-branch: true
          title: 'Bump report'
          body: |
            Bump report
            ${{ env.NV }}
          labels: |
            report
            automated pr
          team-reviewers: |
            owners
            maintainers
          draft: false
